version: '3.1'

services:

  db:
    image: mariadb:10.11

    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080

